// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Strudent.proto

package com.example.proto;

public interface StreamResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.proto.StreamResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string response_info = 2;</code>
   */
  java.lang.String getResponseInfo();
  /**
   * <code>string response_info = 2;</code>
   */
  com.google.protobuf.ByteString
      getResponseInfoBytes();
}
