// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Strudent.proto

package com.example.proto;

public interface StreamRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.proto.StreamRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string request_into = 1;</code>
   */
  java.lang.String getRequestInto();
  /**
   * <code>string request_into = 1;</code>
   */
  com.google.protobuf.ByteString
      getRequestIntoBytes();
}
