// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Strudent.proto

package com.example.proto;

public interface StudentRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.proto.StudentRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 age = 1;</code>
   */
  int getAge();
}
